sudo: required
dist: trusty

# install google chrome for UI tests
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "10"

# cache node_modules directories
cache:
  directories:
    - client/node_modules
    - server/node_modules
    - node_modules


# start virtual frame buffer
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  # execute all tests
  - npm run test

  # build documentation
  - cd client
  - npm run compodoc

# deploy to GitHub Pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: client/documentation
  on:
    branch: master
