version: "3"

services:
  client:
    build: ./client
    restart: unless-stopped
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    environment:
    - LETSENCRYPT_HOST=vacation.mani94.space
    - VIRTUAL_HOST=vacation.mani94.space
    - LETSENCRYPT_EMAIL=manuel.leitold1@gmail.com
    - VIRTUAL_PORT=80
    depends_on:
      - server

  server:
    build: ./server
    restart: unless-stopped
    volumes:
      - db:/usr/share/app/db_data

volumes:
  db:
